### ISSUE TITLE
How to set notifications when all/particular sets of jobs are completed

### ISSUE THREAD

**Issue by ghost** [lykmapipo/sails-hook-publisher#1]
super useful hook - thanks; have a question:
in my /models/email.js, I'm creating the following job in my afterCreate lifecycle callback:

var emailJob = publisher.create('email', {
            title: "emailing the following url: " + urlPath,
            url: urlPath
        }).save();

in config/bootstrap.js, I have the .on('job complete'), but that gets trigger when each/any of the jobs is done 

my question is:
a) how/where do i set a trigger when a particular 'email' job is done
b) how/where do i set a trigger when all the 'email' jobs are done 
c) how/where do i set a trigger when all jobs are done (i.e the queue is empty)

Thanks :-)

**Comment by lykmapipo** [comment]
@codefullon 

sails-hook-publisher uses [kue](https://github.com/Automattic/kue) on its implementation.
If you look at its [queue](https://github.com/lykmapipo/sails-hook-publisher/blob/master/index.js#L76), its just an instance of kue.

So,
- how/where do i set a trigger when a particular 'email' job is done

Well this follow the same description given at [Job Events](https://github.com/Automattic/kue#job-events). All you have to attach event listener when you publish your job.

``` js
//publish send confirmation email
var job = publisher.create('email', {
title: 'Welcome', 
to: request.email,
template: 'welcome-email'
});

//attach your listeners
job.on('complete', function(result){
  console.log('Job completed with data ', result);

}).on('failed attempt', function(errorMessage, doneAttempts){
  console.log('Job failed');

}).on('failed', function(errorMessage){
  console.log('Job failed');

}).on('progress', function(progress, data){
  console.log('\r  job #' + job.id + ' ' + progress + '% complete with data ', data);

});

//finally save the job
 job.save();
```
- how/where do i set a trigger when all the 'email' jobs are done
  Base on [kue](https://github.com/Automattic/kue#overview) this has not yet been
  implemented in the core so you have to track your jobs.
- how/where do i set a trigger when all jobs are done (i.e the queue is empty)
  Same as above

But the above two issues can be addressed by implementing a job that will be watching if all jobs (or jobs) of the given type are done.

Hope it helps.

**Comment by ghost** [comment]
thanks @lykmapipo , the job events solved it :-)
