### ISSUE TITLE
jobs get stuck in inactive/failed state

### ISSUE THREAD

**Issue by ghost** [lykmapipo/sails-hook-publisher#2]
I have a worker that extracts links from a web page- not sure why but this particular worker (unlike 4 which are working fine) either
a) gets stuck in inactive state
b) fail
one of the things is that this does not always happen which each of the jobs this worker finishes, so that's where the confusion is

Here's the code for the above mentioned worker: http://pastebin.com/xGhPcBt9

What i want to learn is:
a) how do i debug what's going wrong
b) what can i do to restart the job it fails - would use .attempt(x) be the best option?
c) how do i get the jobs to force continue if it gets stuck in inactive mode and nothing is really happening, atm what i have to do is restart the sails server after which the inactive jobs start processing but after some gets done, again the queue gets hanged

thanks :D

**Comment by lykmapipo** [comment]
@codefullon 

Is this supposed not supposed to be an issue on [sails-hook-subscriber](https://github.com/lykmapipo/sails-hook-subscriber). It it will be helpfully for others to open it on sails-hook-subscriber repo to track its problem the problems.

Please consider to close this issue and reopen in [sails-hook-subscriber](https://github.com/lykmapipo/sails-hook-subscriber) repo.

YW.

**Comment by ghost** [comment]
thanks @lykmapipo just posted it on the subscriber repo :-)
