### ISSUE TITLE
A way to disable it

### ISSUE THREAD

**Issue by ajkaanbal** [lykmapipo/sails-hook-publisher#3]
Maybe like this: https://github.com/sgress454/sails-hook-autoreload/blob/master/index.js#L17

**Comment by lykmapipo** [comment]
@ajkaanbal 

I working on that. Hope next release will have it.

Thanks.

**Comment by lykmapipo** [comment]
@ajkaanbal 

Fixed on v0.2.0

**Comment by ajkaanbal** [comment]
Thanks, man!
